import pandas as pd
import os

sentences_3 = [
    "Fashionable shoes are a key element in modern clothing styles.",
    "The durability of shoes greatly depends on the material used.",
    "High heels add a touch of elegance to any shoe.",
    "Sneakers are the perfect blend of comfort and casual style.",
    "Horses, as majestic mammals, have a powerful presence.",
    "The horse's tail is a distinctive feature, expressive and graceful.",
    "Horses have played a significant role in human travel history.",
    "Riding a horse is an exhilarating and skillful experience.",
    "A knife is a versatile tool in culinary arts.",
    "The precision of knife blades is crucial for effective cutting.",
    "A knife can be a dangerous weapon if misused.",
    "A careful stab with a knife is key in precise cooking.",
    "Cod is a widely favored fish in culinary dishes.",
    "The flesh of cod is known for its tender texture.",
    "Cod dishes are celebrated for their delicious and versatile flavors.",
    "Freshly caught cod is a treat in seafood cuisine.",
    "Train stations are bustling centers of travel and activity.",
    "The locomotive is the powerful driving force of a train.",
    "Freight trains play a vital role in transporting goods.",
    "Commuter trains are essential in daily urban transportation.",
    "A house is a permanent structure providing safety and comfort.",
    "The roof is an integral part of a house's structure.",
    "Different rooms in a house serve various purposes.",
    "A house is made a home by the people inside it.",
    "Water is a vital liquid essential for all life forms.",
    "Drinking water is crucial for maintaining good health.",
    "Water freezes into ice, a natural phenomenon of beauty.",
    "Rain, the water from the sky, nourishes the earth.",
    "Floods occur when water overflows beyond its normal confines.",
    "Heavy rainfall can lead to severe flood conditions.",
    "Rivers can flood their banks, affecting nearby areas.",
    "Evacuating during floods can prevent major tragedies.",
    "Hospitals are centers where people go to be healed.",
    "Well-staffed hospitals are crucial for providing quality care.",
    "Hospitals cater to patients with diverse medical needs.",
    "Efficient hospital operations are vital for patient care.",
    "A tomato's red color signifies its ripeness and flavor.",
    "As a tomato softens, it reaches its peak flavor.",
    "Tomato salads are a fresh and healthy meal option.",
    "There are numerous tomato varieties, each with unique characteristics.",
    "Dress clothing often signifies style and sophistication.",
    "Long dresses add a sense of elegance to formal events.",
    "Formal dresses are essential for special ceremonial occasions.",
    "Climbing in a dress combines grace with adventure.",
    "Floors should be horizontal and sturdy in any building.",
    "The choice of floor material can define a space's ambiance.",
    "Floor carpets add comfort and aesthetic value to rooms.",
    "The floor beneath us provides stability and support.",
    "Solid walls are fundamental to a building's stability.",
    "Walls offer support and help define spaces within buildings.",
    "Brick walls have been a reliable choice for centuries.",
    "Retaining walls are crucial for preventing soil erosion.",
    "Blenders are a staple in any modern kitchen.",
    "Glass blenders are both durable and visually appealing.",
    "Blending fruit in a blender makes delicious smoothies.",
    "Blenders are perfect for creating a variety of drinks.",
    "Unlawful murder is a grave and serious offense.",
    "Serious murder investigations require thorough examination and expertise.",
    "Murder is a significant crime with heavy legal consequences.",
    "Being convicted of murder leads to severe legal repercussions."
]

sentences_4 = [
    "Shoes are the final touch to any clothing ensemble.",
    "Shoe material choice significantly impacts both style and comfort.",
    "Heels can transform shoes into a statement of elegance.",
    "Sneakers are the epitome of comfort in shoe fashion.",
    "The horse, a majestic mammal, symbolizes strength and freedom.",
    "A horse's tail is a unique feature, expressive in movement.",
    "Historic horse travel revolutionized human mobility and exploration.",
    "Horse riding combines skill, balance, and connection with nature.",
    "A knife, more than a tool, is a chef's ally.",
    "Knife blades require expert crafting for precision and durability.",
    "In certain situations, a knife becomes more than a weapon.",
    "A skilled stab with a knife is essential in culinary arts.",
    "Cod, a versatile fish, is a favorite in many cuisines.",
    "Cod flesh, known for its tenderness, enhances many dishes.",
    "Creative cod dishes are a highlight in seafood cuisine.",
    "The freshness of caught cod is unmatched in flavor.",
    "Train stations are the crossroads of journeys and stories.",
    "The train locomotive stands as a symbol of enduring power.",
    "Freight trains are essential arteries of global commerce.",
    "Commuter trains are the heartbeats of urban mobility.",
    "A house is a permanent sanctuary for its dwellers.",
    "A house's roof stands guard against the elements.",
    "Each room in a house reflects its own story.",
    "Houses are more than structures; they are filled with life.",
    "Water, in its liquid form, is vital for existence.",
    "Drinking water is fundamental to life and health.",
    "The magic of water freezing into ice fascinates us all.",
    "Rain is the earth's way of replenishing its water.",
    "Floods represent the overwhelming power of nature's water.",
    "Heavy rains often lead to challenging flood situations.",
    "Flooded rivers remind us of nature's uncontrollable force.",
    "Timely evacuation can be crucial during a flood.",
    "Hospitals are where people go to find healing.",
    "Hospitals rely on well-trained staff for efficient care.",
    "Caring for hospital patients requires empathy and expertise.",
    "Hospital operations are a complex ballet of skill and precision.",
    "The red color of tomatoes signals their ripeness and taste.",
    "As a tomato softens, it's ready for culinary use.",
    "Tomato salads are both healthy and bursting with flavor.",
    "Different tomato varieties offer a range of culinary possibilities.",
    "Dress clothing often symbolizes elegance and special occasions.",
    "Long dresses bring a sense of sophistication to any event.",
    "Formal dresses are essential for elegant social gatherings.",
    "Climbing in a dress can be a daring fashion statement.",
    "Floors provide a horizontal base for every space.",
    "The material of a floor defines the room's character.",
    "Floor carpets add a layer of comfort and style.",
    "Floors form the foundation of our daily lives.",
    "Walls provide essential support and define spaces.",
    "Walls bear the weight and stories of buildings.",
    "Brick walls are known for their strength and longevity.",
    "Retaining walls are crucial for landscape stability.",
    "Blenders are a kitchen's versatile appliance for various concoctions.",
    "Glass blenders combine aesthetic appeal with functionality.",
    "Blending fruits in a blender creates delightful smoothies.",
    "Blenders are perfect for mixing up a variety of drinks.",
    "Murder, an unlawful act, shatters the moral order.",
    "Serious murder cases challenge the very core of justice.",
    "Murder, a heinous crime, is vehemently condemned.",
    "Conviction for murder carries profound legal consequences."
]

sentences_5 = [
    "Shoes, an essential part of clothing, define style and comfort.",
    "The quality of shoe material directly impacts durability and aesthetics.",
    "Heels on shoes can elevate both stature and sophistication.",
    "Sneakers: the perfect blend of style and athletic functionality.",
    "Horses, as majestic mammals, embody strength and grace.",
    "The swaying horse tail signifies elegance and agility.",
    "Throughout history, horses have been pivotal in human travel.",
    "A horse ride offers a unique blend of adventure and skill.",
    "A knife, more than a tool, is an extension of the chef's hand.",
    "The sharpness of knife blades is crucial in culinary precision.",
    "A knife, while a tool, can also be a formidable weapon.",
    "A precise stab with a knife is essential in gourmet cooking.",
    "Cod, a versatile fish, is beloved in culinary circles.",
    "Cod flesh is renowned for its delicate texture and flavor.",
    "A variety of cod dishes grace tables worldwide.",
    "Freshly caught cod promises a feast of freshness.",
    "Train stations are bustling hubs of journey and discovery.",
    "The locomotive pulls the train with formidable strength.",
    "Freight trains are vital in the transportation of goods.",
    "Commuter trains are the lifeblood of urban transit.",
    "A house is a permanent symbol of safety and comfort.",
    "A sturdy roof is integral to a house's protection.",
    "The rooms in a house tell stories of its inhabitants.",
    "A house becomes a home when filled with loving people.",
    "Water, in its liquid state, is vital for all life.",
    "Drinking water is essential for survival and health.",
    "When water freezes, it turns into beautiful ice.",
    "Water from rain is crucial for the Earth's ecosystems.",
    "Floods can cause dramatic overflows of natural water bodies.",
    "Heavy rain often leads to serious flood conditions.",
    "Overflowing rivers during floods pose significant threats.",
    "Evacuation is a key safety measure during floods.",
    "Hospitals are havens of healing and recovery.",
    "A well-staffed hospital is essential for efficient healthcare.",
    "Hospital patients receive care from dedicated professionals.",
    "Hospital operations require precision, skill, and coordination.",
    "The red hue of tomatoes is a mark of ripeness.",
    "As tomatoes soften, they become ready for culinary use.",
    "Tomato salads are a fresh, nutritious dining choice.",
    "Different tomato varieties offer a range of tastes and textures.",
    "Dress clothing often represents elegance and personal style.",
    "Long dresses are synonymous with grace and sophistication.",
    "Formal dresses are essential for special, elegant events.",
    "Climbing in a dress can be a unique fashion statement.",
    "A horizontal floor is the foundation of any building.",
    "The choice of floor material impacts the room's ambiance.",
    "Carpets on floors add comfort and aesthetic value.",
    "The floor under our feet provides stability and support.",
    "Solid walls are crucial for structural integrity.",
    "Walls provide support and shape to any building.",
    "Brick walls combine durability with aesthetic appeal.",
    "Retaining walls are essential for preventing soil erosion.",
    "Blenders are versatile tools in the modern kitchen.",
    "Glass blenders add a touch of elegance to kitchen appliances.",
    "Blending fruit creates delicious and healthy smoothies.",
    "Blenders are ideal for preparing a variety of drinks.",
    "Unlawful murder is a deeply disturbing and serious crime.",
    "Serious murder investigations demand thoroughness and expertise.",
    "Murder, a grievous act, is severely punished by law.",
    "Convicted murderers face serious legal consequences."
]


# Create a DataFrame from the new set of generated sentences
df_new_sentences = pd.DataFrame(sentences_5, columns=["Generated Sentences"])

# Save the DataFrame to a new Excel file
new_output_excel_path = os.path.join('processed_data', 'LLM_sentences5.xlsx')
df_new_sentences.to_excel(new_output_excel_path, index=False)